### ISSUE TITLE
Seems to only detect one Steam Library at a time.

### ISSUE THREAD

**Issue by Doctor-Dank** [tappi287/openvr_fsr_app#3]
Seems to only detect one steam library at a time.

If you have multiple libraries over a few disks it wont detect more than one, and there appears to be no way to add them manually.

**Comment by Julian-MJK** [comment]
I'm having this issue as well, I have all my games on other drives, my main drive is the SSD I use for Windows and regular programs.
So please add an option to change the steam library path

**Comment by Adil3tr** [comment]
I am as well, steam is on my small boot drive and all my games are on other drives. I think a lot of people will have this issue since the most heavy games tend to be the largest in file size and more likely to be installed on larger secondary drives.

**Comment by MrDecepticon** [comment]
I have multiple steam library locations and none are on my system drive so this tool doesn't find any games at all.

**Comment by IkumaVR** [comment]
it looks as if I have this problem too

**Comment by tappi287** [comment]
Hi, thanks for reporting. I'll add an option to add custom paths. Still to narrow down the error could some of you please execute this in an command line:
`REG QUERY "HKEY_CURRENT_USER\Software\Valve\Steam" /v SteamPath`
Go to the path that is display, go into the subfolder "steamapps" and open the file "libraryfolders.vdf" with an editor and post the contents? That is where the app accquires the library paths.

**Comment by Altalus** [comment]
Here's mine. I have the same issue where my main boot SSD is not where I host the games. Oh, and a Linux option would be very cool for my 2nd rig :P

```
"libraryfolders"
{
	"contentstatsid"		"263799398697174331"
	"1"
	{
		"path"		"T:\\SteamLibrary"
		"label"		""
		"contentid"		"5877056926329381406"
		"totalsize"		"536870907904"
		"apps"
		{
		}
	}
	"2"
	{
		"path"		"D:\\SteamLibrary"
		"label"		""
		"contentid"		"3094077687235149111"
		"totalsize"		"2000381014016"
		"apps"
		{
			"225540"		"64613856054"
			"227300"		"12805956726"
			"244210"		"44949522749"
			"270880"		"7628018560"
			"378860"		"54160546915"
			"383120"		"9731286804"
			"440900"		"124291564423"
			"460930"		"75188144023"
			"491540"		"13469076080"
			"637650"		"112895080187"
			"739630"		"14581046533"
			"824000"		"4867453482"
			"870780"		"45986935160"
			"955610"		"3019585638"
			"979690"		"18762806333"
			"1080110"		"44637457963"
			"1088770"		"13759407891"
			"1250410"		"1162668728"
			"1358140"		"7070045884"
			"1702920"		"991221103"
		}
	}
	"3"
	{
		"path"		"E:\\SteamLibrary"
		"label"		""
		"contentid"		"5856589001625490079"
		"totalsize"		"6997044883456"
		"apps"
		{
		}
	}
}

```

**Comment by MrDecepticon** [comment]
Hmm, weird.  Mine is " SteamPath    REG_SZ    c:/program files (x86)/steam"  but I have a steam library on almost every single drive.

**Comment by tappi287** [comment]
Nice, thank you for the input. All my other machines use a different format inside the libraryfolders.vdf. This is fixed with 0.2.1

**Comment by MrDecepticon** [comment]
This still does not work.  I downloaded 0.2.1, completely removed old version, installed 0.2.1 and it still does not see my libraries.

**Comment by Altalus** [comment]
I have to vote to also re-open this issue. I tested the new version but I still only see "SteamVR" as the only app listed.

**Comment by Doctor-Dank** [comment]
Did not fix for me either @tappi287

**Comment by tappi287** [comment]
Can you try this version and see if it works? It's quite painful that the Steam config files do not seem to follow the same rules on every system...
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.2.2

**Comment by tappi287** [comment]
Cool, then thanks for the report and continued testing. Closing this
