### ISSUE TITLE
VrPerfKit Uknown Version

### ISSUE THREAD

**Issue by cassell1337** [tappi287/openvr_fsr_app#48]
i previously had open_fsr mod installed so i uninstalled it and removed the dll then used steam to verify and nothing is missing it says but in vr mod app it says "VrPerfKit Uknown Version" and i dont have that installed or anything the game is phasmaphobia just incase thats needed

**Comment by cassell1337** [comment]
it also says the file can be found when trying to uninstall

**Comment by cassell1337** [comment]
honestly no idea how i fixed it just kept restarting app and updating and then it finally said nothing was installed weird

**Comment by archead** [comment]
Having a similar issue with Assetto Corsa, deleted the DLLs and verified integrity, issue remained.
I am running Content Manager + CSP if that matters.
![image](https://user-images.githubusercontent.com/55419973/163750457-e03f752c-a458-4575-8edd-2e097f20642b.png)

**Comment by tappi287** [comment]
The behaviour has changed for VRP plugin dll's that had been manually removed by users:
https://github.com/tappi287/openvr_fsr_app/releases/tag/0.9.8

**Comment by archead** [comment]
Thank you for looking into this.
